version: 2
jobs:
  build:
    working_directory: ~/skeleton
    docker:
      - image: crystallang/crystal:latest
    steps:
      - checkout
      - run:
          name: Install dependencies.
          command: shards install
      - save_cache: # Step to save dependency cache
          key: dependency-cache-{{ checksum "shard.lock" }}
          paths:
            - ./lib
      - run:
          name: test
          command: crystal spec src/*.cr
      - run:
          name: Generate Docs
          command: crystal docs
  docs-deploy:
    docker:
      - image: node:latest
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "me262thanos@gmail.com"
            git config user.name "Oblivious-Oblivious"
      - run:
          name: Deploy docs to gh-pages
          command: gh-pages --dotfiles --message "Updates" --dist docs/
