version: 2
jobs:
  build:
    working_directory: ~/skeleton
    docker:
      - image: crystallang/crystal:latest
    steps:
      - checkout
      - run:
          name: Install dependencies.
          command: shards install
      - save_cache: # Step to save dependency cache
          key: dependency-cache-{{ checksum "shard.lock" }}
          paths:
            - ./lib
      - run:
          name: test
          command: crystal spec src/*.cr
      - run:
          name: Generate Docs
          command: crystal docs